name: Firebase Hosting CI/CD

on:
  push:
    branches:
      - main  # or your default branch (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository's code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment with a compatible version (>=18)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Updated to Node.js 18 (compatible with Firebase CLI)

    # Install Firebase CLI
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    # Authenticate with Firebase using the token stored in the secret
    - name: Authenticate to Firebase
      run: firebase login --token ${{ secrets.FIREBASE_AUTH_TOKEN }}

    # Deploy to Firebase Hosting (if you already have the static files)
    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --project your-project-id
